name: 'Github Actions PoC'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Import SSH Key
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        ssh-add - <<< "${SSH_KEY}"

    - name: Clone private repo - test
      env:
        REPO: git@github.com:msfidelis/atlantis-pipeline.git
      run: |
        git clone $REPO